플레이어 이동, 인벤토리 기능, 무기 줍기 구현
revokim/Project_MJ pull request #10
Opened 2024-11-08 14:04 UTC by ChocoThief

2024-11-09 05:09 UTC, SkyLightQP requested changes
전체적으로
- `namespace` 팀 컨벤션에 맞춰 통일
- 필요없는 주석 삭제 (아래 상세 설명)

가 필요합니다.

Player, MainScene에서 충돌이 발생하는데 Player는 적절하게 수정하면 될 것 같고
MainScene의 경우 테스트로 넣은 오브젝트는 정리하여 수정 후 충돌 해결하면 될 것 같습니다.

추가적으로 주석의 경우
- 최상단 글로벌 변수를 선언할 때(플레이어 스탯, 인벤토리 슬롯 등)에는 용어와 의미 통일을 위해 주석을 다는 것은 좋지만
  - 따라서 위 케이스는 별도 리뷰를 올리지 않았습니다. 지금 상태를 유지해도 좋을 것 같습니다.
- 이후 로직 부분에서 메소드 이름이나 조건문에 의도를 전달하기 위해 달 필요는 없다고 생각합니다.
  - 메소드의 경우 내부 로직이 복잡해서 바로 파악이 되지 않는 규모가 아니고,
  - 설령 위와 같은 일이 발생하면 코드 설계적으로 무언가 잘못이 있다는 뜻입니다.
  - 조건문의 경우 한 번에 파악이 힘든 복잡한 조건문이 존재할 수 있지만, 이 경우 리뷰를 통해 언급한 '조건문을 별도 변수로 분리하기' 방법을 이용하면 좋을 것 같습니다.

코드 품질 외 유니티, 유니티 최적화와 관련된 부분은 별도 리뷰가 필요합니다.

2024-11-09 05:09 UTC, SkyLightQP commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +namespace Code.Scripts.Inventory
namespace 통일 필요

2024-11-09 05:09 UTC, SkyLightQP commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +            switch (input.y)
switch 구문을 쓰는 것도 좋지만 이분법으로 나뉘는 상황의 경우 if 문을 사용하면 간략하게 표현이 가능합니다.
```c#
// Example
if (input.y > 0) // TODO: Action
else // TODO: Action
```
switch, if 문의 차이는 개발자 취향 차이에 불구하기 때문에 더 편한 방법을 사용하면 될 것 같습니다.

2024-11-09 05:09 UTC, SkyLightQP commented on Assets/Code/Scripts/Inventory/InventoryUI.cs
> +            _inven.onInvetoryCursorChanged += RedrawCursorUI;
원래 유니티에서는 대입(`=`) 이 아니라 `+=` 연산으로 넣나요?

2024-11-09 05:09 UTC, SkyLightQP commented on Assets/Code/Scripts/Player.cs
> +            _playerMoveSpeed = 5.0f;
추후 변경될 일이 없는 상수 값이라면 선언과 동시에 `5.0` 값읗 넣어줘도 될 것 같습니다.

2024-11-10 14:46 UTC, ChocoThief commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +            SelectedSlotNum = 0;
Inventory class 29번 줄에 있습니다

2024-11-10 14:47 UTC, ChocoThief commented on Assets/Code/Scripts/Player.cs
> +            _playerMoveSpeed = 5.0f;
이동 속도가 아직 정해진게 아니라 추후에 수정하겠습니다

2024-11-10 14:47 UTC, ChocoThief commented on Assets/Code/Scripts/Inventory/InventoryUI.cs
> +            _inven.onInvetoryCursorChanged += RedrawCursorUI;
델리게이트 변수에 함수 할당해줄 때는 += 문법 쓰는 걸로 알고 있습니다

2024-11-10 14:53 UTC, ChocoThief commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +namespace Code.Scripts.Inventory
수정해습니당

2024-11-10 14:53 UTC, ChocoThief commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +        public bool AddItemToInventory(CollectibleItem weapon) //무기 인벤토리 리스트에 추가
수정했습니당

2024-11-10 14:53 UTC, ChocoThief commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +        //델리게이트들
확인했습니당

2024-11-10 14:53 UTC, ChocoThief commented on Assets/Code/Scripts/CollectibleItem.cs
> +namespace Code.Scripts
수정헀습니당

2024-11-10 14:53 UTC, ChocoThief commented on Assets/Code/Scripts/CollectibleItem.cs
>  ﻿// 맵 상에 드랍되는 경험치, 재화, 장비를 다루는 클래스입니다.
확인했습니당.

2024-11-11 00:10 UTC, SkyLightQP approved these changes

2024-11-12 14:15 UTC, merged

2024-11-13 02:31 UTC, revokim commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +            if (bagWeapons.Count < _bagSlotCount) //가방 슬롯 남으면 추가
거짓말쟁이

2024-11-13 02:31 UTC, revokim commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +
```c#
private void RemoveItem(int index){
    if(index < 0) // 가방
    else(index >= 0) // Equip
    
   
    
    onInventoryItemChanged.Invoke();
}

 List asdf = (index > 0 )? baglist : invenlist;
    asdf.removeat(index); //jungwon
```

2024-11-13 02:31 UTC, revokim commented on Assets/Code/Scripts/Inventory/Inventory.cs
> +        private void OnSwapWeaponPerformed(InputAction.CallbackContext context) // 무기 변경 입력 받기
On 하는 애들의 cost에 대해 알아보면 재밌을거 같아요

2024-11-13 02:31 UTC, revokim commented on Assets/Code/Scripts/ItemPickupManager.cs
> +        private GameObject _letterEIcon; //무기
명칭 수정