weapons
revokim/Project_MJ pull request #11
Opened 2024-11-08 14:27 UTC by P4HB

무기 생성, 관리 등 스크립트 작성 (영역형 무기 제외)

2024-11-09 05:23 UTC, SkyLightQP requested changes
브랜치가 엉켜있어 일반 Merge를 사용하면 히스토리가 지저분해질 것 같습니다.
리뷰 완료 후 머지 할 때 **반드시 Squash Merge를 사용해주세요.**

2024-11-09 05:23 UTC, SkyLightQP commented on Assets/Code/Scripts/Bullet.cs
> +        public void Init(int weaponID, float attackDamage, int piercing, float bulletSpeed, Vector3 direction)
Bullet이 초기화(`Awake` 발생)되기 전에 `Init()`이 호출되는 경우가 있을 것 같습니다.
이미 19번째 라인에서 체크를 하고 있긴하나, 이 보다는 `_rigidbody`가 `Null`일 때 Exception을 발생시켜서 아에 게임 실행이 안되게 하는 게 나아보입니다. 현재 방식으로 사용되면 Nullable 상태가 계속 하위로 전파될 것 같습니다.

2024-11-09 05:23 UTC, SkyLightQP commented on Assets/Code/Scripts/Weapon.cs
>      // 모든 종류의 무기에 공통적으로 들어가는 요소들을 지정합니다.
```suggestion
```
주석 삭제

2024-11-09 05:23 UTC, SkyLightQP commented on Assets/Code/Scripts/Weapon.cs
> +                case 0 : // 무기가 롱소드 인 경우
무기ID를 단순 정수형으로 관리 중인데 Human Error가 발생할 가능성이 있습니다.
**추후,** 해당 부분을 Enum으로 관리하거나 또는 정수형의 ID가 아닌 문자열 형태의 Code로 관리해도 좋을 것 같습니다.

2024-11-09 05:23 UTC, SkyLightQP commented on Assets/Code/Scripts/Weapon.cs
> +        private IEnumerator LongswordAttack()
무기의 형태마다 계속 메소드를 추가하여 액션을 구현하고 있는데,
지금 당장은 문제가 없지만 무기가 몇십개 단위로 늘어날 경우 유지보수가 어려워보입니다.
이 역시 **추후**에 interface를 적용하여 분리하거나 Strategy 패턴을 적용하는 등으로 개선이 가능할 것 같습니다.

2024-11-13 09:39 UTC, P4HB commented on Assets/Code/Scripts/Weapon.cs
> +                case 0 : // 무기가 롱소드 인 경우
아직 무기 DB 구현을 안한 상태인데 레벨에 따른 무기 속성 구현 하면 무기 ID를 int 로 하는거는 딱히 상관 없지 않나요? 괜히 리스트랑 딕셔너리 쓰는데 코드만 복잡해질 것 같기도해서

2024-11-13 09:40 UTC, P4HB commented on Assets/Code/Scripts/Weapon.cs
> +        private IEnumerator LongswordAttack()
일단 테스트할때는 이런식으로 하고 나중에 코드 간소화 하는 방법을 한번 고려해볼게요

2024-11-14 01:32 UTC, revokim requested changes
:)

2024-11-14 01:32 UTC, revokim commented on Assets/Code/Scripts/Bullet.cs
> +        public void Init(int weaponID, float attackDamage, int piercing, float bulletSpeed, Vector3 direction)
변수와 함수 간에 단락 구분 부탁드립니다 + private public 간 또는 유사한 변수 묶음들을 구분지어서 단락구분을 지어주는 것도 좋습니다

```suggestion

        public void Init(int weaponID, float attackDamage, int piercing, float bulletSpeed, Vector3 direction)
```

2024-11-14 01:32 UTC, revokim commented on Assets/Code/Scripts/Bullet.cs
> +            if (_rigidbody != null)
위의 하대겸 병장님 코멘트랑 유사한 이야기인데, null체크 하신 이유가 궁금합니다

2024-11-14 01:32 UTC, revokim commented on Assets/Code/Scripts/Bullet.cs
> +        void OnTriggerEnter2D(Collider2D collision)
접근 제한자 설정해주시면 좋을 것 같아요

2024-11-14 01:32 UTC, revokim commented on Assets/Code/Scripts/BulletPool.cs
> +            Instance = this;
```suggestion
            Instance = this;
            DontDestroyOnLoad(gameObject);
```

불릿 풀이 의도되지 않게 여러개 생성될 수 있으니, DontDestroyOnLoad를 추가하는 것이 좋을 것 같습니다

2024-11-14 01:32 UTC, revokim commented on Assets/Code/Scripts/BulletPool.cs
> +        if (bulletPools.ContainsKey(weaponID) && bulletPools[weaponID].Count > 0)
지금 bulletPolls를 ContainsKey와 bulletPools[weaponID]로 두 번 조회하는데,
TryGetValue 써서 한 번 체크하면 좋을 것 같아요

2024-11-14 01:33 UTC, SkyLightQP approved these changes

2024-11-14 03:10 UTC, P4HB commented on Assets/Code/Scripts/BulletPool.cs
> +        if (bulletPools.ContainsKey(weaponID) && bulletPools[weaponID].Count > 0)
trygetvalue 써도 어차피 bool 값이랑 나오는 int 값 둘다 체크해야해서 오히려 더 복잡할것 같아요

2024-11-14 03:24 UTC, P4HB commented on Assets/Code/Scripts/BulletPool.cs
> +        if (bulletPools.ContainsKey(weaponID) && bulletPools[weaponID].Count > 0)
하륜씨 저 컨플릭트 해결하려고 rebase 하다가 또 다 날아갔는데 어떻게 할까요

2024-11-14 05:49 UTC, revokim commented on Assets/Code/Scripts/BulletPool.cs
> +        if (bulletPools.ContainsKey(weaponID) && bulletPools[weaponID].Count > 0)
```c#
            if (bulletPools.TryGetValue(weaponID, out Queue<GameObject> pool) && pool.Count > 0)
            {
                GameObject bullet = pool.Dequeue();
                bullet.SetActive(true);
                return bullet;
            }
            else if (bulletPrefabs.TryGetValue(weaponID, out GameObject bulletPrefab))
```

2024-11-14 09:35 UTC, revokim approved these changes

2024-11-14 09:35 UTC, merged