GameManager: 싱글톤화, 플레이어 변수 저장, 경험치 획득 함수 및 레벨업 구조
revokim/Project_MJ pull request #13
Opened 2024-11-12 15:27 UTC by ChocoThief

2024-11-12 23:32 UTC, SkyLightQP approved these changes

2024-11-13 02:33 UTC, revokim requested changes
exp 형 확인

2024-11-13 02:33 UTC, revokim commented on Assets/Code/GameManager.cs
> +        public int[] nextExp = {10, 30 ,60, 100, 150, 210, 280, 360, 450, 600};
exp 현재 float로 설정되어 있는걸로 알아서 확인 후 수정 부탁드립니다.

2024-11-13 14:32 UTC, ChocoThief commented on Assets/Code/GameManager.cs
> +        public int[] nextExp = {10, 30 ,60, 100, 150, 210, 280, 360, 450, 600};
수정했습니당

2024-11-14 06:01 UTC, revokim approved these changes

2024-11-14 23:25 UTC, merged