[Feat] Implement character, enemy, weapon, particle class
revokim/Project_MJ pull request #7
Opened 2024-10-29 14:11 UTC by Blackmint1120

2024-10-29 14:31 UTC, revokim requested changes

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/Character.cs
> +﻿namespace Code.Scripts
네임스페이스는 스크립트입니다. 같은 느낌보다는. 무엇을 위한 모듈들인지를 나타낼 수 있는 네이밍을 사용하는 편이 좋습니다.

Code.Scripts 보다는 MJ.Character 로 하는 편이 좋고, 적은 MJ.Enemy 와 같은 식으로 하나의 모듈화를 시키는 느낌으로 생각해주시면 좋습니다.

EnumTypes는 namespace MJ 정도로만 해도 괜찮겠죠?

이유는 MJ안에 속해있는 애들이 다 사용하게 될거기 때문에 그렇다고 생각해요.

하지만 제가 적는게 정답은 아니니, 다른 Namespace활용 예시와, Namespace를 사용하는 근본적인 이유에 대해 조금 더 공부해보면 좋을 것 같습니다. 저도 공부해보고 공유드릴게요.

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/Character.cs
> +		private int _hp; //체력
탭이 이상하네요

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/Character.cs
> +    public class Character
Character보다는 Player가 더 적당한 네이밍일 것 같네요

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/Character.cs
> +        private int _atk; // 공격력
공격력은 int 보다는 float나 double을 사용해야 비율로 성장하는 데 있어서 반영이 정상적으로 이루어질 것 같습니다.

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/Character.cs
> +		private int _hp; //체력
체력과 경험치도요!

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/Enemy.cs
> +        private int _atk; // 적 공격력
Character.cs에 있는 atk와 혼동할 수도 있기 때문에 변수명을

playerATK
enemyATK

와 같이 하면 좋을 것 같고,
hp도 함께 봐주시면 될 것 같습니다.

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/Particle.cs
> +    public class Particle
CollectibleItem 으로 가시죠

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/EnumTypes.cs
> +        Credit,
gold 어떠신가요
이거는 기획에서 재화명을 얘기해서 정해주시면 좋을 것 같습니다.

2024-10-29 14:31 UTC, revokim commented on Assets/Code/Scripts/Weapon.cs
> +{
앞에 using UnityEngin; 들어가야하나요? 다 빠져있는데, 기본 코드에도 들어가야 하는지는 모르겠어요. 그리고 기본적으로 모노비헤이비어로 만드는게 디폴트인데, 이것도 확인해주시면 될 것 같습니다.

2024-10-30 03:58 UTC, Blackmint1120 commented on Assets/Code/Scripts/Character.cs
> +﻿namespace Code.Scripts
좋은 지적입니다. 수정 예정입니다.

2024-10-30 04:01 UTC, Blackmint1120 commented on Assets/Code/Scripts/Character.cs
> +    public class Character
수정 완료했습니다~

2024-10-30 05:13 UTC, Blackmint1120 commented on Assets/Code/Scripts/Character.cs
> +        private int _atk; // 공격력
좋은 지적입니다. 수정했습니다~

2024-10-30 05:27 UTC, Blackmint1120 commented on Assets/Code/Scripts/EnumTypes.cs
> +        Credit,
이건 논의 후 수정하는 것으로 하겠습니다~!

2024-10-30 05:27 UTC, Blackmint1120 commented on Assets/Code/Scripts/Enemy.cs
> +        private int _atk; // 적 공격력
전반적으로 적용 완료하고, 추가로 변수 이름도 좀 더 직관적으로 수정했습니다~

2024-10-30 05:33 UTC, Blackmint1120 commented on Assets/Code/Scripts/Weapon.cs
> +{
한번 알아봤는데, using UnityEngine은 enum 코드 정도 제외하면 미리 넣어두면 좋을 것 같고, MonoBehaviour도 비슷한 것 같네요

2024-10-30 05:49 UTC, revokim commented on Assets/Code/Scripts/Enemy.cs
> +    }
이동속도만 추가하면 좋을 것 같아요!

2024-10-30 05:49 UTC, revokim commented on Assets/Code/Scripts/Player.cs
> +    }
여기도 이동속도 추가하면 좋을 것 같아요.

2024-10-30 05:49 UTC, revokim commented on Assets/Code/Scripts/Weapon.cs
> +{
넵 좋습니다!

2024-10-30 06:07 UTC, revokim approved these changes
너무 좋습니다! 고생하셨습니다!

2024-10-30 06:08 UTC, merged